name: MiniGameHub
version: "${project.version}"
main: org.maven.minigamehub.MiniGameHub
api-version: "1.21"
author: "Meesz"
commands:
  minigame:
    description: Command to manage mini-games
    usage: /minigame start <game> <players>

